# docker-compose.production.yml
services:
  runtime:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: nestjs-runtime
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - redis
      - elasticsearch
      - rabbitmq
    environment:
      NODE_ENV: production
    env_file:
      - .env.production