services:
  postgres:
    image: postgres:14
    container_name: postgres-app
    restart: unless-stopped
    environment:
      POSTGRES_USER: app_postgres_user
      POSTGRES_PASSWORD: app_postgres_password
      POSTGRES_DB: app_postgres_db
    ports:
      - "5432:5432"
    volumes:
      - /Volumes/Data/docker/postgres:/var/lib/postgresql/data  # only this is mounted
    # Nếu dùng VPS:
    # - /var/vps-data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data  # internal volume

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data  # internal volume
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpassword
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq  # internal volume

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-dev
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules  # local code only
    depends_on:
      - postgres
      - redis
      - elasticsearch
      - rabbitmq
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env.development

volumes:
  redis-data:
  es-data:
  rabbitmq-data: